cs412/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("hw/", include("hw.urls")),
    path("quotes/", include("quotes.urls")),
    path("formdata/", include("formdata.urls")),
    path("restaurant/", include("restaurant.urls")),
    path("blog/", include("blog.urls")),
    path("mini_insta/", include("mini_insta.urls")),
    path("voter_analytics/", include("voter_analytics.urls")),
    path("dadjokes/", include("dadjokes.urls")),
    path("project/", include("project.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hw/urls.py
# file: hw/urls.py

from django.urls import path
from django.conf import settings #?
from . import views

# URL patterns specific to the hw app
urlpatterns = [
    #path(r'', views.home, name='home'),
    path(r'', views.home_page, name="home_page"),
    path(r'about', views.about_page, name="about_page"),
]

project/urls.py
# file: project/urls.py
# Sulaf Al Jabal (sulafaj@bu.edu) 11/24/25
# URL patterns for final project application

from django.urls import path
from django.conf import settings 
from .views import *

urlpatterns = [
    # Home page
    path('', HomeView.as_view(), name='home'),
    
    # Main list views
    path('doctors', DoctorListView.as_view(), name='doctors'),
    path('nurses', NurseListView.as_view(), name='nurses'),
    path('patients', PatientListView.as_view(), name='patients'),
    path('appointments', AppointmentListView.as_view(), name='appointments'),

    # Detail views
    path('patient/<int:pk>', PatientDetailView.as_view(), name='patient'),
    path('nurse/<int:pk>', NurseDetailView.as_view(), name='nurse'),
    path('doctor/<int:pk>', DoctorDetailView.as_view(), name='doctor'),
    path('appointment/<int:pk>', AppointmentDetailView.as_view(), name='appointment'),

    # Calendar views
    path('appointment_calendar/', CalendarView.as_view(), name='appointment_calendar'),
    path('day_schedule/', DayScheduleView.as_view(), name='day_schedule'),
    
    # Appointment management
    path('create_appointment/', CreateAppointmentView.as_view(), name='create_appointment'),
    path('delete_appointment/<int:pk>/', DeleteAppointmentView.as_view(), name='delete_appointment'),
    
    # Patient management
    path('create_patient/', CreatePatientView.as_view(), name='create_patient'),
    path('update_patient/<int:pk>/', UpdatePatientView.as_view(), name='update_patient'),
    
    # Doctor management
    path('create_doctor/', CreateDoctorView.as_view(), name='create_doctor'),
    path('update_doctor/<int:pk>/', UpdateDoctorView.as_view(), name='update_doctor'),
    
    # Nurse management
    path('create_nurse/', CreateNurseView.as_view(), name='create_nurse'),
    path('update_nurse/<int:pk>/', UpdateNurseView.as_view(), name='update_nurse'),
]

project/models.py
# project/models.py
# Sulaf Al Jabal (U78815065) 11/20/2025
# File Description: where all models of final project will be defined

from django.db import models
import datetime

# Create your models here.

class Patient(models.Model):
    """Definition of Patient model"""
    firstName = models.TextField(blank=True)
    lastName = models.TextField(blank=True)
    middleName = models.TextField(blank=True)
    DOB = models.DateField(auto_now=False)
    primaryCareDoctor = models.ForeignKey("Doctor", on_delete=models.CASCADE, blank=True, null=True)
    address = models.TextField(blank=True)
    picture = models.ImageField(blank=True)

    @property
    def age(self):
        """Calculates the patient's current age."""
        today = datetime.date.today()
        return today.year - self.DOB.year - (
            (today.month, today.day) < (self.DOB.month, self.DOB.day)
        )
    #enddef

    @property
    def isAdult(self):
        """Returns 'A' for adult or 'C' for child based on Patient age."""
        if self.age >= 18:
            return 'Adult'
        return 'Child'
    #enddef


    def __str__(self):
        """ Returning string representation of Patient object """
        pcd = 'No' if self.primaryCareDoctor == None else f"{self.primaryCareDoctor.lastName}, {self.primaryCareDoctor.firstName}"
        return f"P: {self.lastName}; {self.firstName}, {self.middleName} | Age: {self.age} | {self.isAdult} | PCD: {pcd}" #PCD: Primary Care Doctor
    #enddef

    def getPrimaryCareDoctor(self):
        """ Returns name of primary care doctor associated with a Patient record or no if this is blank"""
        if self.primaryCareDoctor == None:
            return "no"
        return self.primaryCareDoctor
    #enddef

#endclass

class Doctor(models.Model):
    """ Definition of Doctor model """
    firstName = models.TextField(blank=True)
    lastName = models.TextField(blank=True)
    specialty = models.TextField(blank=True) # this might need to change later for Doctor search capabilities
    picture = models.ImageField(blank=True)

    def __str__(self):
        """ Returning string representation of Doctor object. 
        This will need to change, not sure what attributes are important here. Maybe start with specialty?"""
        return f"D: {self.lastName}, {self.firstName} | {self.specialty}"
    #enddef

#endclass

class Nurse(models.Model):
    """ Definition of Nurse model """
    firstName = models.TextField(blank=True)
    lastName = models.TextField(blank=True)
    picture = models.ImageField(blank=True)


    def __str__(self):
        """ Returning string representation of Nurse object. Similar issue to Doctor object"""
        return f"N: {self.lastName}, {self.firstName}"
    #enddef

    def getPicture(self):
        if self.picture == None:
            return 'media\Default_pfp.jpg'.url
        return self.picture.url
#endclass

class Appointment(models.Model):
    """ Definition of Appointment model 
    Attributes:
    patient: primary key of patient
    dateTime: Date and Time of appointment
    problem: text field with name of problem
    problemDescription: text field with description of the wider patient ailment
    appointmentType: char field. Defined options of appointment types. This serves mostly as a shorthand description of the appointment type.
    The only field I suspect will cause tangible issues with the application as a whole will be the ('ER', "Emergency Care) option since it might force 
    me to add double-booking for nurses and doctors (more accurately represents what hospital scheduling is like, but might cause me great issues later down the road)"""

    app_choices = [
        ('CU', 'Checkup'),
        ('PO', "Post Operation"),
        ('SP', "Specialist Consultation"),
        ("FU", "Follow-up Visit"),
        ("NA", "Nurse Appointment"), 
        ("PE", "Pre-operation Visit"),
        ("CO", "Counselling Session"),
        ("TH", "Telehealth/Virtual Visit"),
        ("VA", "Vaccination Appointment"),
        ("A", "Annual Checkup"),
        ("BC", "Birth Control Consultation"),
        ("MC", "Medication Check"), # reserved typically for children taking specific medications
    ]
    # this is set at a certain time for a date in the future, so it can't make use of auto_now
    patient = models.ForeignKey("Patient", on_delete=models.CASCADE)
    dateTime = models.DateTimeField(auto_now=False)
    problem = models.TextField() # main description of problem
    problemDescription = models.TextField()
    appointmentType= models.CharField(
        max_length = 2,
        choices=app_choices
    ) # choices already defined above, new ones can be added as time goes on
    # dont think I need to include DoctorProvider and NurseProvider since the appointmentID will be added to those
    # record

    def __str__(self):
        """Returns a string representation of Appointment record"""
        return f"P: {self.patient.lastName}, {self.patient.firstName} | {self.patient.age} | {self.dateTime.date()} {self.dateTime.time()} | {self.appointmentType} | {self.problem}"
    #enddef

    def get_nurses(self):
        """ Creating a method to get all nurses associated with this appointment. This helper function is used at least
        twice in the application, once to show the specific details of any individual Appointment record, and another time
        within the Patient Detail View"""

        nurse_list = []
        nurse_provider = list(NurseProvider.objects.filter(appointmentID=self.pk))
        for n in nurse_provider:
            nurse_list.append(Nurse.objects.filter(pk=n.nurseID.pk)[0]) # this might be a queryset
        #endfor

        return nurse_list
    #enddef

    def get_doctors(self, **kwargs):
        """ Creating a method to get all doctors associated with this appointment record."""
        doctor_list = []
        doctor_provider = list(DoctorProvider.objects.filter(appointmentID=self.pk))
        for d in doctor_provider:
            doctor_list.append(Doctor.objects.filter(pk=d.doctorID.pk)[0])
        #endfor
        return doctor_list
    #enddef

#endclass

class DoctorProvider(models.Model):
    """ Helper model which allows certain appointments to have multiple providers (Doctor)
    If multiple doctors will be present at an appointment, then multiple records of the DoctorProvider table will share the
    same appointmentID
    Attributes:
    appointmentID: links to Appointment table
    doctorID: PK of doctor if they are working on a certain appointment (can be blank if this is a Nurse only appointment)
    """
    appointmentID = models.ForeignKey("Appointment", on_delete=models.CASCADE)
    doctorID = models.ForeignKey("Doctor", on_delete=models.CASCADE)

    def __str__(self):
        """ Returning string representation of DoctorProvider record"""
        doctor = Doctor.objects.filter(pk=self.doctorID.pk)[0]
        app = Appointment.objects.filter(pk=self.appointmentID.pk)[0]
        return f"D: {doctor.firstName} {doctor.lastName} | {doctor.specialty} | {app.dateTime.date()} {app.dateTime.time()} "
    #enddef

#endclass

class NurseProvider(models.Model):
    """ Helper model which allows certain appointments to have multiple providers (Nurse)
    If multiple nurses will be present at an appointment, then multiple records of theNurseProvider table will share the same
    appointmentID
    Attributes:
    appointmentID: links to Appointment table
    nurseID"""
    appointmentID = models.ForeignKey("Appointment", on_delete=models.CASCADE)
    nurseID = models.ForeignKey("Nurse", on_delete=models.CASCADE)

    def __str__(self):
        """Returning string representation of NurseProvider object"""
        nurse = Nurse.objects.filter(pk=self.nurseID.pk)[0]
        app = Appointment.objects.filter(pk=self.appointmentID.pk)[0]
        return f"N: {nurse.firstName} {nurse.lastName} | {app.dateTime.date()} {app.dateTime.time()} "
#endclass

project/templates/project/appointment_calendar.html
<!-- file: templates/project/appointment_calendar.html
 Sulaf Al Jabal (U78815065) 12/02/2025
 File description: html template responsible for showing calendar view of each month, appointments for each day of the month populate the screen-->
{% extends 'project/base.html' %}
{% block content %}

<h2>Appointment Calendar - {{ current_month|date:"F Y" }}</h2>

<div>
    <a href="{% url 'appointment_calendar' %}?{{ prev_month }}"> &lt;&lt; Previous Month </a>
    <a href="{% url 'appointment_calendar' %}"> Today </a>
    <a href="{% url 'appointment_calendar' %}?{{ next_month }}"> Next Month &gt;&gt; </a>
    <a href="{% url 'day_schedule' %}"> Day Schedule View </a>
</div>

<p><em>Click on any day number to see detailed schedule for that day</em></p>

<div>
    {{ calendar }}
</div>

<!-- Debug info 
<div>
    <h3>Debug Information:</h3>
    <p><strong>Current Month Viewing:</strong> {{ current_month|date:"F Y" }}</p>
    <p><strong>Total Appointments in Database:</strong> {{ object_list.count }}</p>
    <p><strong>Appointments THIS month ({{ current_month|date:"F Y" }}):</strong> {{ appointments_this_month.count }}</p>
    <ul>
    {% for appointment in appointments_this_month %}
        <li>{{ appointment.patient.lastName }}, {{ appointment.patient.firstName }} - {{ appointment.dateTime }}</li>
    {% empty %}
        <li>No appointments found for {{ current_month|date:"F Y" }}</li>
    {% endfor %}
    </ul>
</div>

{% endblock %}
 -->

project/templates/project/appointment_search.html
<!-- /templates/project/appointment_search.html 
 Sulaf Al Jabal (U78815065) 11/24/25
 file description: html template for searching appointments, embedded into project/appointments.html page-->
 
 
<table>
<form action="{% url 'appointments' %}">

<tr>
    <th>Appointment Type:</th>
    <td>
        <select name="appointmentType" id="appointmentType">
            <option value="">All Types</option>
            {% for code, display in appointment_types %}
                <option value="{{code}}">{{display}}</option>
            {% endfor %}
        </select>
    </td>
</tr>

<tr>
    <th>Doctor:</th>
    <td>
        <select name="doctor" id="doctor">
            <option value="">Any Doctor</option>
            {% for d in doctors %}
                <option value="{{d.pk}}">{{d.lastName}}, {{d.firstName}}</option>
            {% endfor %}
        </select>
    </td>
</tr>

<tr>
    <th>Nurse:</th>
    <td>
        <select name="nurse" id="nurse">
            <option value="">Any Nurse</option>
            {% for n in nurses %}
                <option value="{{n.pk}}">{{n.lastName}}, {{n.firstName}}</option>
            {% endfor %}
        </select>
    </td>
</tr>

<tr>
    <th>Patient Name:</th>
    <td><input type="text" name="patient_name" placeholder="Search by patient name"></td>
</tr>

<tr>
    <th>Date Range:</th>
    <td>
        From: <input type="date" name="date_from">
        To: <input type="date" name="date_to">
    </td>
</tr>

<tr>
    <td><input type="submit" value="Search"></td>
    <td></td>
</tr>

</form>

</table>

project/templates/project/appointments.html
<!--templates/project/appointments.html
Sulaf Al Jabal (U78815065) 11/24/25
File description: html template to showcase all records of appointments, organized by time-->

{% extends 'project/base.html' %}
 
{% block content %}
<h1>Showing all Appointment records</h1>

<div class="container">
        
        <div class="row">
            {% include "project/appointment_search.html" %}
        </div>
        <a class="buttons" href="{% url 'appointments' %}">Clear Filters</a>
        <div>
            <a href="{% url 'create_appointment' %}">
                <button type="button">Create New Appointment</button>
            </a>
        </div>
 
    <div class="row">
        {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li>
                    <span><a href="?{{ request.GET.urlencode }}&page={{ page_obj.previous_page_number }}">Previous</a></span>                
                </li>
            {% endif %}
                <li class="">
                    <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
                </li>
            {% if page_obj.has_next %}
                <li>
                    <span><a href="?{{ request.GET.urlencode }}&page={{ page_obj.next_page_number }}">Next</a></span>
                </li>
            {% endif %}
            </ul>
        {% endif %}
    </div>
    
	<!-- table of results -->
    <div class="row">
        <table>
            
            <tr>
                <th>Date & Time</th>
                <th>Patient</th>
                <th>Appointment Type</th>
                <th>Problem</th>
                <th>Doctor(s)</th>
                <th>Nurse(s)</th>
            </tr>
    
            {% for a in appointments %}
            <tr>
                <td>
                    <a href="{% url 'appointment' a.pk %}">
                        {{a.dateTime|date:"m/d/Y g:i A"}}
                    </a>
                </td>
                <td>
                    <a href="{% url 'patient' a.patient.pk %}">
                        {{a.patient.lastName}}, {{a.patient.firstName}}
                    </a>
                </td>                 
                <td>{{a.get_appointmentType_display}}</td>
                <td>{{a.problem}}</td>
                <td>
                    {% for doctor in a.get_doctors %}
                        <a href="{% url 'doctor' doctor.pk %}">{{doctor.lastName}}</a>{% if not forloop.last %}, {% endif %}
                    {% empty %}
                        None
                    {% endfor %}
                </td>
                <td>
                    {% for nurse in a.get_nurses %}
                        <a href="{% url 'nurse' nurse.pk %}">{{nurse.lastName}}</a>{% if not forloop.last %}, {% endif %}
                    {% empty %}
                        None
                    {% endfor %}
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
 
</div>    
{% endblock %}

project/templates/project/base.html
<!-- project/base.html
 Sulaf Al Jabal (U78815065) 11/24/25
 file description: base html template for entire project-->

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hospital Scheduling Application</title>
    <link rel="stylesheet" href="{% static 'project/styles.css' %}">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'patients' %}">Patients</a></li>
                <li><a href="{% url 'doctors' %}">Doctors</a></li>
                <li><a href="{% url 'nurses' %}">Nurses</a></li>
                <li><a href="{% url 'appointments' %}">Appointments</a></li>
                <li><a href="{% url 'appointment_calendar' %}">Calendar</a></li>
                <li><a href="{% url 'day_schedule' %}">Today's Schedule</a></li>
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <p>Hospital Scheduling Application &copy; 2025</p>
        <p>Current Time: {{ current_time|date:"F d, Y g:i A" }}</p>
    </footer>
</body>
</html>

project/templates/project/create_appointment.html
<!-- file: templates/project/create_appointment.html
 Sulaf Al Jabal (U78815065) 12/06/2025
 Decsription: html template which displays form responsible for creating an appointment-->
{% extends 'project/base.html' %}

{% block content %}

<h2>Create New Appointment</h2>

<form method="post">
    {% csrf_token %}
    
    <table>
        {{ form.as_table }}
    </table>
    
    <br>
    <input type="submit" value="Create Appointment">
    <a href="{% url 'day_schedule' %}">Cancel</a>
</form>

{% if form.errors %}
    <div>
        <h3>Errors:</h3>
        {{ form.errors }}
    </div>
{% endif %}

{% endblock %}

project/templates/project/doctor.html
<!-- project/doctor.html
 Sulaf Al Jabal (U78815065) 11/24/25
 file description: html template dedicated to showing details about a certain doctor record-->

{% extends 'project/base.html' %}

{% block content %}

<h2>Doctor: {{doctor.firstName}} {{doctor.lastName}}</h2>
{% if doctor.picture %} 
    <img src="{{doctor.picture.url}}" alt="Picture of {{doctor.firstName}} {{doctor.lastName}}" width="200">
{% else %}
    <img src="../../../media/Default_pfp.jpg" alt="No picture associated with this doctor" width="200">
{% endif %}

<p>Specialty: {{doctor.specialty}}</p>

<h3>Administrative Actions</h3>
<div>
    <a href="{% url 'update_doctor' doctor.pk %}">
        <button type="button">Update Doctor Information</button>
    </a>
</div>

{% endblock %}

project/templates/project/doctor_form.html
<!-- project/doctor_form.html
 Sulaf Al Jabal (U78815065) 12/07/25
 file description: html template for creating or updating doctor records-->

{% extends 'project/base.html' %}

{% block content %}

{% if form.instance.pk %}
    <h2>Update Doctor: {{form.instance.firstName}} {{form.instance.lastName}}</h2>
{% else %}
    <h2>Create New Doctor</h2>
{% endif %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    <table>
        {{ form.as_table }}
    </table>
    
    <br>
    
    {% if form.instance.pk %}
        <input type="submit" value="Update Doctor">
        <a href="{% url 'doctor' form.instance.pk %}">Cancel</a>
    {% else %}
        <input type="submit" value="Create Doctor">
        <a href="{% url 'doctors' %}">Cancel</a>
    {% endif %}
</form>

{% if form.errors %}
    <div>
        <h3>Errors:</h3>
        {{ form.errors }}
    </div>
{% endif %}

{% endblock %}

project/templates/project/doctors.html
<!--templates/project/doctors.html
Sulaf Al Jabal (U78815065) 11/24/25
File description: html template to showcase all records of Doctors-->

{% extends 'project/base.html' %}

{% block content %}

<h2>Showing all doctors</h2>
<h3>Click on a doctor's name to view their information</h3>

<div>
    <a href="{% url 'create_doctor' %}">
        <button type="button">Create New Doctor</button>
    </a>
</div>

<br>

{% for d in doctors %}
    <a href = "{% url 'doctor' d.pk %}">
        <p>{{d.firstName}} {{d.lastName}} - {{d.specialty}}</p>
    </a>
{% endfor %}
{% endblock %}

project/templates/project/home.html
<!-- project/home.html
 Sulaf Al Jabal (U78815065) 12/07/25
 file description: Home page for hospital scheduling application - information for administrators-->

{% extends 'project/base.html' %}

{% block content %}

<h1>Hospital Scheduling Application</h1>
<h2>Administrative Dashboard</h2>

<p>Welcome to the Hospital Scheduling Application. This system is designed for administrative staff to manage patient appointments, staff assignments, and medical records.</p>

<hr>

<h3>System Overview</h3>

<h4>Patient Management</h4>
<ul>
    <li><strong>View All Patients:</strong> Browse and search through all patient records</li>
    <li><strong>Filter Patients:</strong> Search by name, age group (adult/child), birth year range</li>
    <li><strong>Create New Patient:</strong> Add new patients to the system with demographic and contact information</li>
    <li><strong>Update Patient Records:</strong> Modify existing patient information including address, primary care doctor, and profile picture</li>
    <li><strong>View Patient History:</strong> See all appointments for any individual patient</li>
</ul>

<h4>Doctor Management</h4>
<ul>
    <li><strong>View All Doctors:</strong> Browse all doctor records in the system</li>
    <li><strong>Create New Doctor:</strong> Add new doctors with specialty information and profile pictures</li>
    <li><strong>Update Doctor Records:</strong> Modify doctor information including specialty and profile picture</li>
    <li><strong>Assign to Appointments:</strong> Assign single or multiple doctors to appointments</li>
</ul>

<h4>Nurse Management</h4>
<ul>
    <li><strong>View All Nurses:</strong> Browse all nurse records in the system</li>
    <li><strong>Create New Nurse:</strong> Add new nurses with profile pictures</li>
    <li><strong>Update Nurse Records:</strong> Modify nurse information and profile pictures</li>
    <li><strong>Assign to Appointments:</strong> Assign single or multiple nurses to appointments</li>
</ul>

<h4>Appointment Management</h4>
<ul>
    <li><strong>View All Appointments:</strong> Browse all scheduled appointments</li>
    <li><strong>Filter Appointments:</strong> Search by appointment type, assigned doctor, assigned nurse, patient name, or date range</li>
    <li><strong>Create New Appointment:</strong> Schedule appointments from:
        <ul>
            <li>Day schedule view (click time slot)</li>
            <li>Patient detail page (pre-fills patient)</li>
            <li>Direct creation form</li>
        </ul>
    </li>
    <li><strong>Delete Appointments:</strong> Remove appointments with confirmation (accessible from appointment detail page only)</li>
    <li><strong>Appointment Types Supported:</strong> Checkups, Post-Operation, Specialist Consultation, Follow-up Visits, Nurse Appointments, Pre-operation Visits, Counseling Sessions, Telehealth Visits, Vaccinations, Annual Checkups, Birth Control Consultations, Medication Checks</li>
</ul>

<h4>Calendar Views</h4>
<ul>
    <li><strong>Month Calendar View:</strong> Visual calendar showing all appointments for a selected month
        <ul>
            <li>Navigate between months</li>
            <li>Click any day number to see detailed day schedule</li>
            <li>See appointment summaries on each day</li>
        </ul>
    </li>
    <li><strong>Day Schedule View:</strong> Hour-by-hour breakdown of appointments for a specific day
        <ul>
            <li>Time slots from 12 AM to 11 PM</li>
            <li>Add appointments directly from any time slot</li>
            <li>See patient, doctor, and nurse information for each appointment</li>
            <li>Navigate between days</li>
        </ul>
    </li>
</ul>

<hr>

<h3>Quick Links</h3>
<p>
    <a href="{% url 'patients' %}"><button type="button">Manage Patients</button></a>
    <a href="{% url 'doctors' %}"><button type="button">Manage Doctors</button></a>
    <a href="{% url 'nurses' %}"><button type="button">Manage Nurses</button></a>
    <a href="{% url 'appointments' %}"><button type="button">View Appointments</button></a>
    <a href="{% url 'appointment_calendar' %}"><button type="button">Calendar View</button></a>
    <a href="{% url 'day_schedule' %}"><button type="button">Today's Schedule</button></a>
</p>

<hr>

<h3>System Statistics</h3>
<ul>
    <li><strong>Total Patients:</strong> {{ total_patients }}</li>
    <li><strong>Total Doctors:</strong> {{ total_doctors }}</li>
    <li><strong>Total Nurses:</strong> {{ total_nurses }}</li>
    <li><strong>Total Appointments:</strong> {{ total_appointments }}</li>
</ul>

{% endblock %}

project/templates/project/nurse.html
<!-- project/nurse.html
 Sulaf Al Jabal (U78815065) 11/24/25
 file description: html template dedicated to showing details about a certain Nurse record-->

{% extends 'project/base.html' %}

{% block content %}

<h2>Nurse: {{nurse.firstName}} {{nurse.lastName}}</h2>
{% if nurse.picture %}
    <img src="{{nurse.picture.url}}" alt="Picture of nurse {{nurse.firstName}} {{nurse.lastName}}" width="200">
{% else %}
    <img src="../../../media/Default_pfp.jpg" alt="No picture associated with this nurse" width="200">
{% endif %}

<h3>Administrative Actions</h3>
<div>
    <a href="{% url 'update_nurse' nurse.pk %}">
        <button type="button">Update Nurse Information</button>
    </a>
</div>

{% endblock %}

project/templates/project/patient.html
<!-- project/patient.html
 Sulaf Al Jabal (U78815065) 11/24/25
 file description: html template dedicated to showing details about a certain Patient record-->

{% extends 'project/base.html' %}

{% block content %}

<h2>Patient: {{patient.firstName}} {{patient.middleName}} {{patient.lastName}}</h2>
{% if patient.picture %}    
    <img src="{{patient.picture.url}}" width="200">
{% else %}
    <img src="../../../media/Default_pfp.jpg" alt="No picture associated with this patient" width="200">
{% endif %}

<p>Address: {{patient.address}}<br>
DOB: {{patient.DOB}} <br>
Age: {{patient.age}} <br>
Is adult? {{patient.isAdult}}<br>
Primary Care Doctor?: {{patient.getPrimaryCareDoctor}}</p>

<h3>Administrative Actions</h3>
<div>
    <a href="{% url 'create_appointment' %}?patient={{patient.pk}}">
        <button type="button">Schedule Appointment for {{patient.firstName}}</button>
    </a>
    <a href="{% url 'update_patient' patient.pk %}">
        <button type="button">Update Patient Information</button>
    </a>
</div>

<h3>{{patient.firstName}}'s Previous Appointments</h3> 
<div>
    <table>
        <tr>
            <th>Appointment Date</th>
            <th>Appointment Time</th>
            <th>Problem</th>
            <th>Type</th>
        </tr>
        {% for a in appointments %}
        <tr>
            <td>
                <a href="{% url 'appointment' a.pk %}">
                    {{a.dateTime|date:"F d, Y"}}
                </a>
            </td>
            <td>{{a.dateTime|date:"g:i A"}}</td>
            <td>{{a.problem}}</td>
            <td>{{a.get_appointmentType_display}}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4">No previous appointments</td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}